fix(SignatureError): `SignatureError` exceptions now point to command
Now, all raised ``SignatureError`` exception messages get prefixed with the
fully qualified function name:

```
Traceback (most recent call last):
  File ".../python/toolr/utils/_signature.py", line 251, in get_signature
    parameter = _parse_parameter(param_name, param, resolved_annotation, parsed_docstring)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python/toolr/utils/_signature.py", line 383, in _parse_parameter
    raise SignatureParameterError(err_msg)
toolr._exc.SignatureParameterError: Arg 'version' has no description in the docstring which is required to generate the help message.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".../.venv/bin/toolr", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File ".../python/toolr/__main__.py", line 37, in main
    registry.discover_and_build(parser)
  File ".../python/toolr/_registry.py", line 234, in discover_and_build
    self._build_parsers()
  File ".../python/toolr/_registry.py", line 218, in _build_parsers
    signature = get_signature(commands[command_name])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python/toolr/utils/_signature.py", line 253, in get_signature
    raise SignatureError(exc.message, func) from exc
toolr._exc.SignatureError: tools.version.commit: Arg 'version' has no description in the docstring which is required to generate the help message.
```

Fixes #27